mongodb:
  # MongoDB connection URI
  uri: "mongodb+srv://legit:shauryam@minecraftservertest.xspyocf.mongodb.net/"
  # Database name
  database: "minecraftservertest"

chat: "&8[FFA] %luckperms_prefix%%player_name% &8» &f{message}"r