name: FFACore
version: '${project.version}'
main: me.legit.ffacore.FFACore
softdepend:
  - PlaceholderAPI
  - WorldEdit
  - WorldGuard
  - LuckPerms
authors: [ Legit ]
description: FFA core plugin
commands:
  ffa:
    description: FFACore admin command
    usage: /ffa reload
    permission: ffacore.admin
  spawn:
    description: Teleport to spawn
    usage: /spawn
  setspawn:
    description: Set spawn location
    usage: /setspawn
    permission: ffacore.admin
  arena:
    description: Manage FFA arenas
    usage: /arena <create|join|delete|setmin|setmax|setactive|list>
    permission: ffacore.admin
  kit:
    description: Select kit
    usage: /kit <kitname>
  kitadmin:
    description: Admin kit GUI
    usage: /kitadmin
    permission: ffacore.admin
  leaderboard:
    description: Manage holographic leaderboards
    usage: /leaderboard <add|movehere|reload|remove|list|update>
    permission: ffacore.admin
    aliases: lb