name: FFACore
version: '${project.version}'
main: me.legit.ffacore.FFACore
softdepend: [ PlaceholderAPI ]
depend: [WorldEdit, LuckPerms]
authors: [ Legit ]
description: FFA core plugin
commands:
  ffa:
    description: FFACore admin command
    usage: /ffa reload
  spawn:
    description: Teleport to spawn
    usage: /spawn
  setspawn:
    description: Set spawn location
    usage: /setspawn
  arena:
    description: Arena management
    usage: /arena create <name>
  kit:
    description: Select kit
    usage: /kit <kitname>
  kitadmin:
    description: Admin kit GUI
    usage: /kitadmin
  leaderboard:
    description: Manage holographic leaderboards
    usage: /leaderboard <add|movehere|reload|remove|list|update>
  lb:
    description: Short alias for /leaderboard
    usage: /lb <add|movehere|reload|remove|list|update>